language: python

env:
  global:
    - APP_SETTINGS="testing"

python:
  - "3.5"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest
  - pip install coverage

before_script:
  - "psql -c 'create database testdb;' -U postgres"

script:
  - python -m pytest tests --cov=api 

after_success:
- coveralls